sudo: required
language: generic
services:
        - docker
before_install:
        - docker build -t ramsureshn/myapp -f Dockerfile.dev .
script:
        - docker run -e CI=true ramsureshn/myapp npm run test
