sudo: required
services:
        - docker
before_install:
        - docker build -t ramsuresh/docker-react -f Dockerfile.dev
script:
        - docker run -c CI=true ramsureshn/docker-react npm run test
