version: '3.8'
services:
        myapp:
          stdin_open: true
          build:
            context: .
            dockerfile: Dockerfile.dev
          ports:
            - "3000:3000"
          volumes:
            - /app/node_modules
            - .:/app
        apptest:
          build:
            context: .
            dockerfile: Dockerfile.dev
          volumes:
            - /app/node_modules
            - .:/app
          command: ["npm", "run", "test"]

